name: Build and Cache Dependencies

on:
  workflow_dispatch:
    inputs:
      run-job1:
        description: 'Run job1'
        required: true
        default: 'false'
        type: string

jobs:
  linux-build:
    if: ${{ github.event.inputs.run-job1 == 'true' }}
    name: Linux Depends Build Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Укажите существующую ветку вместо 'working'
          ref: ${{ github.ref_name }}  # Использует текущую ветку
          # Или явно укажите основную ветку:
          # ref: main
          # ref: master
          # ref: develop

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build Linux Depends
        run: |
          cd depends
          make -j$(nproc)

  windows-build:
    name: Windows Depends Build Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}  # Использует текущую ветку

      - name: Install Mingw-w64
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            autoconf \
            automake \
            libtool \
            pkg-config \
            mingw-w64

      - name: Build Windows Depends
        run: |
          cd depends
          make HOST=x86_64-w64-mingw32 NO_QT=1 -j$(nproc)
