name: Build and Cache Dependencies

on:
  workflow_dispatch:
    inputs:
      run-job1:
        description: 'Run job1'
        required: true
        default: 'false'
        type: string

jobs:
  linux-build:
    if: ${{ github.event.inputs.run-job1 == 'true' }}
    name: Linux Depends Build Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
         ref: working

      - name: Change ownership of APT cache
        run: sudo chown -R $USER:$USER /var/cache/apt
      
      - name: Restore APT cache
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('apt-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-${{ hashFiles('apt-requirements.txt') }}
            ${{ runner.os }}-apt-
      - name: Set up depends cache
        id: cache
        uses: actions/cache@v4
        with:
          path: depends/x86_64-pc-linux-gnu
          key: ${{ runner.os }}-x86_64-pc-linux-gnu-${{ hashFiles('depends/packages/**') }}

      - name: Run Make
        run: |
          cd depends
          make -j$(nproc)
  windows-build:
    name: Windows Depends Build Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
         ref: working

      - name: Change ownership of APT cache
        run: sudo chown -R $USER:$USER /var/cache/apt
      
      - name: Restore APT cache
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('apt-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-${{ hashFiles('apt-requirements.txt') }}
            ${{ runner.os }}-apt-
    
      - name: Set up depends cache
        id: cache
        uses: actions/cache@v4
        with:
          path: depends/x86_64-w64-mingw32
          key: ${{ runner.os }}-x86_64-w64-mingw32-${{ hashFiles('depends/packages/**') }}

      - name: Install MinGW-w64 cross-compilers
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 g++-mingw-w64-x86-64
      - name: Run Make
        run: |
          export PATH=/usr/local/gcc-mingw/bin:$PATH
          sudo update-alternatives --install /usr/bin/x86_64-w64-mingw32-g++ x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix 100
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
          sudo update-alternatives --install /usr/bin/x86_64-w64-mingw32-gcc x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix 100
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          x86_64-w64-mingw32-g++-posix --version
          x86_64-w64-mingw32-gcc-posix --version
          cd depends/ && make HOST=x86_64-w64-mingw32 V=1 NO_QT=1